api_platform:
    title: 'API for simple blog platform'
    version: '0.1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    collection:
        pagination:
            page_parameter_name: _page
            client_enabled: true
            items_per_page: 10
            maximum_items_per_page: 50
    exception_to_status:
        # Custom mapping
        App\Exception\EmptyBodyException: 400 # Here is the handler for our custom exception
