vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /images/media_objects
            upload_destination: '%kernel.project_dir%/public/images/media_objects'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
