vich_uploader:
    db_driver: orm

    mappings:
        blog_images:
            uri_prefix: /images/blog_images
            upload_destination: '%kernel.project_dir%/public/images/blog_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
